Fix build failure on arm64 due to unsigned char
C char is signed on amd64 and unsigned on arm64.
https://github.com/rust-lang/rust/blob/d3e1ccdf40ae7b7a6dc81edc073d80dad7b66f75/library/core/src/ffi/primitives.rs#L37-L133

This results in a compilation failure on arm64:

	error[E0308]: mismatched types
	   --> src/lib.rs:225:27
	    |
	225 |     if (*sample.event) == 'b' as i8 {
	    |        ---------------    ^^^^^^^^^ expected `u8`, found `i8`
	    |        |
	    |        expected because this is `u8`

Update to use c_char in this cast instead of i8.